baseURL: "https://jthcheung.github.io" 
title: CHEUNG, Tsz Him (Jason)
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Background
          url: background/
          weight: 1 
        - name: Publications
          url: papers/
          weight: 2
        - name: Coursework
          url: courses/
          weight: 3
        - name: Teaching Assistantship
          url: teaching/
          weight: 4 
   #     - name: Data
   #       url: data/
   #       weight: 4 
   #     - name: Blog
   #       url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
   #       weight: 6

params:
    description: "I am currently a third-year Ph.D. student at the University of Chicago. have a strong research interest in investigating environmental determinants of health, focusing on climated-related exposures and health equity. <br><br>I earned my B.A. at the University of Hong Kong, where I developed a passion for epidemiology during my senior year. Following this, I received statistical and econometric training and completed an M.Phil. in Social Science at the Hong Kong University of Science and Technology."
    author: CHEUNG, Tsz Him (Jason)
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["background","papers","courses","teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: CHEUNG, Tsz Him (Jason)
          subtitle: "I am currently a third-year Ph.D. student at the University of Chicago. I have a strong research interest in investigating environmental determinants of health, focusing on climated-related exposures and health equity. <br><br>I earned my B.A. at the University of Hong Kong, where I developed a passion for epidemiology during my senior year. Following this, I received statistical and econometric training and completed an M.Phil. in Social Science at the Hong Kong University of Science and Technology."
          #imageWidth: 160
          #imageHeight: 160
          imageWidth: 200
          imageHeight: 200
          imageUrl: "headshot2.jpg"
          imageTitle: CHEUNG, Tsz Him (Jason)
          buttons:
            - name: Background
              url: background/
            - name: Publications
              url: papers/
            - name: Coursework
              url: courses/
            - name: Teaching Assistantship
              url: teaching/
            #- name: Books
            #  url: books/
            #- name: Tags
            #  url: tags/
            #- name: Archive
            #  url: archive/
            #- name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        #- name: CV
        #  url: cv.pdf
        - name: Email
          url: mailto:jasoncheung@uchicago.edu
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        #- name: GitHub
        #  url: https://github.com/pmichaillat
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@alexandermccallsmithoffici9000
        #- name: Twitter
        #  url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "CHEUNG, Tsz Him (Jason)"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
