baseURL: "https://jthcheung.github.io" 
title: CHEUNG, Tsz Him (Jason)
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
    #    - name: Books
    #      url: books/
    #      weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
   #     - name: Data
   #       url: data/
   #       weight: 4 
   #     - name: Blog
   #       url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
   #       weight: 6

params:
    description: "<p>I am a former second-year Ph.D. student in the Department of Public Health Sciences at the University of Chicago, where I focused on the social and environmental determinants of health and health interventions for populations facing behavioral, mental health, and social vulnerabilities. In 2023, I concluded my training and relocated to Hong Kong due to family commitments. I am now seeking a new Ph.D. opportunity in Hong Kong to continue my academic journey.<br><br>I hold an M.Phil. in Social Science from the Hong Kong University of Science and Technology and have research experience in epidemiology from my time as a research assistant at the University of Hong Kong.</p>"   
    author: CHEUNG, Tsz Him (Jason)
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: CHEUNG, Tsz Him (Jason)
          subtitle: "<p>I am a former second-year Ph.D. student in the Department of Public Health Sciences at the University of Chicago, where I focused on the social and environmental determinants of health and health interventions for populations facing behavioral, mental health, and social vulnerabilities. In 2023, I concluded my training and relocated to Hong Kong due to family commitments. I am now seeking a new Ph.D. opportunity in Hong Kong to continue my academic journey.<br><br>I hold an M.Phil. in Social Science from the Hong Kong University of Science and Technology and have research experience in epidemiology from my time as a research assistant at the University of Hong Kong.</p>"  
          imageWidth: 160
          imageHeight: 160
          imageUrl: "/headshot.JPG"
          imageTitle: CHEUNG, Tsz Him (Jason)
          buttons:
            - name: Papers
              url: papers/
            - name: Coursework
              url: courses/
            #- name: Data
            #  url: data/
            #- name: Books
            #  url: books/
            #- name: Tags
            #  url: tags/
            #- name: Archive
            #  url: archive/
            #- name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jasoncheung@uchicago.edu
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        #- name: GitHub
        #  url: https://github.com/pmichaillat
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@alexandermccallsmithoffici9000
        #- name: Twitter
        #  url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "CHEUNG, Tsz Him (Jason)"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
