baseURL: "https://jthcheung.github.io" 
title: CHEUNG, Tsz Him (Jason)
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Background
          url: background/
          weight: 1 
        - name: Publications
          url: papers/
          weight: 2
        - name: Coursework
          url: courses/
          weight: 3
        - name: Teaching Assistantship
          url: teaching/
          weight: 4 
   #     - name: Data
   #       url: data/
   #       weight: 4 
   #     - name: Blog
   #       url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
   #       weight: 6

params:
    description: "I have strong research interest in investigating social and environmental determinants of health, focusing on health interventions for populations with behavioral, mental health, and social vulnerabilities. My goal is to translate research findings into real-world impact.<br><br>I earned my B.A. at the University of Hong Kong, where I developed a passion for epidemiology during my senior year. Following this, I received statistical and econometric training and completed an M.Phil. in Social Science at the Hong Kong University of Science and Technology. I then pursued a Ph.D. in Public Health Sciences at the University of Chicago. In my second year, I concluded my training and relocated to Hong Kong due to family commitments. I am now seeking a new Ph.D. opportunity in Hong Kong to continue my academic journey!"
    author: CHEUNG, Tsz Him (Jason)
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["background","papers","courses","teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: CHEUNG, Tsz Him (Jason)
          subtitle: "I have strong research interest in investigating social and environmental determinants of health, focusing on health interventions for populations with behavioral, mental health, and social vulnerabilities. My goal is to translate research findings into real-world impact.<br><br>I earned my B.A. at the University of Hong Kong, where I developed a passion for epidemiology during my senior year. Following this, I received statistical and econometric training and completed an M.Phil. in Social Science at the Hong Kong University of Science and Technology. I then pursued a Ph.D. in Public Health Sciences at the University of Chicago. In my second year, I concluded my training and relocated to Hong Kong due to family commitments. I am now seeking a new Ph.D. opportunity in Hong Kong to continue my academic journey!"
          #imageWidth: 160
          #imageHeight: 160
          imageWidth: 200
          imageHeight: 200
          imageUrl: "headshot.jpg"
          imageTitle: CHEUNG, Tsz Him (Jason)
          buttons:
            - name: Background
              url: background/
            - name: Publications
              url: papers/
            - name: Coursework
              url: courses/
            - name: Teaching Assistantship
              url: teaching/
            #- name: Books
            #  url: books/
            #- name: Tags
            #  url: tags/
            #- name: Archive
            #  url: archive/
            #- name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jasoncheung@uchicago.edu
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        #- name: GitHub
        #  url: https://github.com/pmichaillat
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@alexandermccallsmithoffici9000
        #- name: Twitter
        #  url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "CHEUNG, Tsz Him (Jason)"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2


#<!-- I am a former second-year Ph.D. student in the Department of Public Health Sciences at the University of Chicago, where I focused on the social and environmental determinants of health and health interventions for populations facing behavioral, mental health, and social vulnerabilities. In 2023, I concluded my training and relocated to Hong Kong due to family commitments. I am now seeking a new Ph.D. opportunity in Hong Kong to continue my academic journey.<br><br>I hold an M.Phil. in Social Science from the Hong Kong University of Science and Technology and have research experience in epidemiology from my time as a research assistant at the University of Hong Kong."-->